#!/usr/bin/env sh

##############################################################################
##
##  Gradle start up script for POSIX generated by Gradle.
##
##############################################################################

DIR="$(cd "$(dirname "$0")" && pwd)"
GRADLE_OPTS="-Dorg.gradle.appname=gradlew"

exec "$DIR/gradle/wrapper/gradle-wrapper.jar" "$@"

